$srv = "C6DBD002"


"DELETE from ccdb2.mdb_reorgchk_index where srvr_nm = '$($srv)';" | Out-Host
"DELETE from ccdb2.mdb_reorgchk_table where srvr_nm = '$($srv)';" | Out-Host
"DELETE from CCDB2.MDB_OBJ_EXCLUDE where srvr_nm = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_DBMS_DATA WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CFG_PARM WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_ODBC_PARM WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_DCS_CATALOG_INFO WHERE SRVR_NM = '$($srv)' ;" | Out-Host
"DELETE FROM CCDB2.MDB_NODE_CATALOG_INFO WHERE SRVR_NM = '$($srv)' ;" | Out-Host
"DELETE FROM CCDB2.MDB_DB_CATALOG_INFO WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_DB_DATA WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_SRVR_SECURITY WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_SRVR_SOFTWARE WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_SRVR_DRIVE WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_SRVR_DATA WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_USERNAME WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_TS_DATA WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CONTAINER_DATA WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_SRVR_EXCLUDE WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CAT_BUFFERPOOLS WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CAT_DBAUTH WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CAT_INDEXCOLUSE WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CAT_INDEXES WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CAT_SERVERS WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CAT_TABAUTH WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CAT_TABLES WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CAT_TABLESPACES WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CAT_TABOPTIONS WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CAT_SERVERS WHERE SRVR_NM = '$($srv)';" | Out-Host
"DELETE FROM CCDB2.MDB_CAT_STMG_DBSIZE_INFO WHERE SRVR_NM = '$($srv)';" | Out-Host

