SELECT * FROM sys.certificates

--SELECT * FROM sys.symmetric_keys

--SELECT * FROM sys.dm_database_encryption_keys

SELECT name, d.is_master_key_encrypted_by_server
FROM sys.databases AS d
WHERE d.name = DB_NAME()

/*
BACKUP SERVICE MASTER KEY TO FILE = '\\blm-bak-10-dd\sql_prod\ENCRYPTION\C1DBD033\C1DBD033_SERVICE_MASTER_KEY_20181116.bsk'   
    ENCRYPTION BY PASSWORD = 'Wba$N4D-L^&CZeJ8'  

BACKUP MASTER KEY TO FILE = '\\blm-bak-10-dd\sql_prod\ENCRYPTION\C1DBD033\C1DBD033_MASTER_KEY_20181116.bmk'   
    ENCRYPTION BY PASSWORD = 'Wba$N4D-L^&CZeJ8'  
GO

BACKUP CERTIFICATE CMS_SecretsCertificate TO FILE = '\\blm-bak-10-dd\sql_prod\ENCRYPTION\C1DBD033\C1DBD033_CMSDB0P1_CERTIFICATE_20181116.bcf'  
    WITH PRIVATE KEY ( FILE = '\\blm-bak-10-dd\sql_prod\ENCRYPTION\C1DBD033\C1DBD033_CMSDB0P1_CERTIFICATE_PRIVATE_KEY_20181116.bpk',
    ENCRYPTION BY PASSWORD = 'Wba$N4D-L^&CZeJ8' );  
GO


*/

CREATE CERTIFICATE CMS_SecretsCertificate FROM FILE ='\\blm-bak-10-dd\sql_prod\ENCRYPTION\C1DBD033\C1DBD033_CMSDB0P1_CERTIFICATE_20181116.bcf'
  WITH PRIVATE KEY(FILE='\\blm-bak-10-dd\sql_prod\ENCRYPTION\C1DBD033\C1DBD033_CMSDB0P1_CERTIFICATE_PRIVATE_KEY_20181116.bpk', 
  DECRYPTION BY PASSWORD='Wba$N4D-L^&CZeJ8');

/*
RESTORE SERVICE MASTER KEY FROM FILE = 
	'\\blm-bak-10-dd\sql_prod\ENCRYPTION\C1DBD033\C1DBD033_SERVICE_MASTER_KEY_20181116.bsk'   
    DECRYPTION BY PASSWORD = 'Wba$N4D-L^&CZeJ8'
*/

/*
RESTORE MASTER KEY   
    FROM FILE = '\\blm-bak-10-dd\sql_prod\ENCRYPTION\C1DBD033\C1DBD033_MASTER_KEY_20181116.bmk'   
    DECRYPTION BY PASSWORD = 'Wba$N4D-L^&CZeJ8'   
    ENCRYPTION BY PASSWORD = '<password>';  
GO 
*/