USE [master]
GO

/****** Object:  Database [ContactManager_SV_1]    Script Date: 1/30/2019 12:51:30 PM ******/
CREATE DATABASE [ContactManager_SV_1]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ContactManager_SV_1', FILENAME = N'L:\Data\ContactManager_SV_1.mdf' , SIZE = 1024000KB , MAXSIZE = 1GB, FILEGROWTH = 1024000KB ), 
 FILEGROUP [ADMIN] 
( NAME = N'ContactManager_SV_1_ADMIN', FILENAME = N'L:\Data\ContactManager_SV_1_ADMIN.ndf' , SIZE = 102400KB , MAXSIZE = 1GB, FILEGROWTH = 102400KB ), 
 FILEGROUP [INDEX] 
( NAME = N'ContactManager_SV_1_INDEX', FILENAME = N'L:\Data\ContactManager_SV_1_INDEX.ndf' , SIZE = 102400KB , MAXSIZE = 1GB, FILEGROWTH = 102400KB ), 
 FILEGROUP [LOB] 
( NAME = N'ContactManager_SV_1_LOB', FILENAME = N'L:\Data\ContactManager_SV_1_LOB.ndf' , SIZE = 102400KB , MAXSIZE = 1GB, FILEGROWTH = 102400KB ), 
 FILEGROUP [OP] 
( NAME = N'ContactManager_SV_1_OP', FILENAME = N'L:\Data\ContactManager_SV_1_OP.ndf' , SIZE = 102400KB , MAXSIZE = 1GB, FILEGROWTH = 102400KB ), 
 FILEGROUP [STAGING] 
( NAME = N'ContactManager_SV_1_STAGING', FILENAME = N'L:\Data\ContactManager_SV_1_STAGING.ndf' , SIZE = 102400KB , MAXSIZE = 1GB, FILEGROWTH = 102400KB ), 
 FILEGROUP [TYPELIST] 
( NAME = N'ContactManager_SV_1_TYPELIST', FILENAME = N'L:\Data\ContactManager_SV_1_TYPELIST.ndf' , SIZE = 102400KB , MAXSIZE = 1GB, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N'ContactManager_SV_1 _log', FILENAME = N'M:\Data\ContactManager_SV_1_log.ldf' , SIZE = 1024000KB , MAXSIZE = 2GB , FILEGROWTH = 1024000KB )
GO

ALTER DATABASE [ContactManager_SV_1] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ContactManager_SV_1].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ContactManager_SV_1] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET ARITHABORT OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ContactManager_SV_1] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ContactManager_SV_1] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ContactManager_SV_1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [ContactManager_SV_1] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ContactManager_SV_1] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ContactManager_SV_1] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ContactManager_SV_1] SET  MULTI_USER 
GO

ALTER DATABASE [ContactManager_SV_1] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ContactManager_SV_1] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ContactManager_SV_1] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ContactManager_SV_1] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ContactManager_SV_1] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ContactManager_SV_1] SET QUERY_STORE = OFF
GO

USE [ContactManager_SV_1]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [ContactManager_SV_1] SET  READ_WRITE 
GO


