CREATE LOGIN [ALLIANCE\XBSHSBQ1_READ_TABVIEW]	FROM WINDOWS;
CREATE LOGIN [ALLIANCE\XBSHSBQ1_UPDATE_TABVIEW]	FROM WINDOWS;
CREATE LOGIN [ALLIANCE\XBSHUBQ1_READ_TABVIEW]	FROM WINDOWS;
CREATE LOGIN [ALLIANCE\XBSHUBQ1_UPDATE_TABVIEW] FROM WINDOWS;
GO

USE [XBSHSBQ1]
CREATE USER [ALLIANCE\XBSHSBQ1_READ_TABVIEW] FOR LOGIN [ALLIANCE\XBSHSBQ1_READ_TABVIEW];
CREATE USER [ALLIANCE\XBSHSBQ1_UPDATE_TABVIEW] FOR LOGIN [ALLIANCE\XBSHSBQ1_UPDATE_TABVIEW];

EXEC sp_addrolemember  @rolename =  'db_datareader',   @membername =  'ALLIANCE\XBSHSBQ1_READ_TABVIEW';
EXEC sp_addrolemember  @rolename =  'db_datareader',   @membername =  'ALLIANCE\XBSHSBQ1_UPDATE_TABVIEW';
EXEC sp_addrolemember  @rolename =  'db_datawriter',   @membername =  'ALLIANCE\XBSHSBQ1_UPDATE_TABVIEW';

USE [XBSHUBQ1]
CREATE USER [ALLIANCE\XBSHUBQ1_READ_TABVIEW] FOR LOGIN [ALLIANCE\XBSHUBQ1_READ_TABVIEW];
CREATE USER [ALLIANCE\XBSHUBQ1_UPDATE_TABVIEW] FOR LOGIN [ALLIANCE\XBSHUBQ1_UPDATE_TABVIEW];


EXEC sp_addrolemember  @rolename =  'db_datareader',   @membername =  'ALLIANCE\XBSHUBQ1_READ_TABVIEW';
EXEC sp_addrolemember  @rolename =  'db_datareader',   @membername =  'ALLIANCE\XBSHUBQ1_UPDATE_TABVIEW';
EXEC sp_addrolemember  @rolename =  'db_datawriter',   @membername =  'ALLIANCE\XBSHUBQ1_UPDATE_TABVIEW';

