WITH instance AS (
SELECT * FROM OPENQUERY(SERVINFO, 
	'SELECT * FROM CCDB2.MDB_DBMS_DATA WHERE DBMS_TYP = ''SQL SERVER''')),
db AS (
SELECT * FROM OPENQUERY(SERVINFO, 
	'SELECT * FROM CCDB2.MDB_DB_DATA WHERE DBMS = ''SQL'''))

SELECT instance.SRVR_NM, COALESCE(COUNT(DB_NM), 0) DBCount
FROM instance
LEFT OUTER JOIN db ON instance.SRVR_NM = db.SRVR_NM
WHERE db.DB_NM NOT IN (
	'MASTER'
	,'MODEL'
	,'MSDB'
	,'REPORTSERVER'
	,'REPORTSERVERTEMPDB'
	,'TEMPDB'
	,'SQLADMIN')
GROUP BY instance.SRVR_NM
ORDER BY DBCount, instance.SRVR_NM