
CREATE LOGIN [ALLIANCE\XBSHSBI1_READ_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHUBI1_READ_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHSBI2_READ_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHUBI2_READ_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHSBI4_READ_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHUBI4_READ_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHSBI5_READ_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHUBI5_READ_TABVIEW]


CREATE LOGIN [ALLIANCE\XBSHSBI1_UPDATE_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHUBI1_UPDATE_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHSBI2_UPDATE_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHUBI2_UPDATE_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHSBI4_UPDATE_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHUBI4_UPDATE_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHSBI5_UPDATE_TABVIEW]
CREATE LOGIN [ALLIANCE\XBSHUBI5_UPDATE_TABVIEW]
