USE [master]
GO
CREATE LOGIN [ALLIANCE\IAAS_Scripts_NONPRD_DDL_ADMIN] FROM WINDOWS WITH DEFAULT_DATABASE=[IAAS_Scripts_NONPRD]
GO
USE [IAAS_Scripts_NONPRD]
GO
CREATE USER [ALLIANCE\IAAS_Scripts_NONPRD_DDL_ADMIN] FOR LOGIN [ALLIANCE\IAAS_Scripts_NONPRD_DDL_ADMIN]
GO
ALTER ROLE [db_datareader] ADD MEMBER [ALLIANCE\IAAS_Scripts_NONPRD_DDL_ADMIN]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [ALLIANCE\IAAS_Scripts_NONPRD_DDL_ADMIN]
GO
GRANT EXECUTE TO [ALLIANCE\IAAS_Scripts_NONPRD_DDL_ADMIN]
GO
GRANT CREATE TABLE TO [ALLIANCE\IAAS_Scripts_NONPRD_DDL_ADMIN]
GO
GRANT CREATE VIEW TO [ALLIANCE\IAAS_Scripts_NONPRD_DDL_ADMIN]
GO
GRANT CREATE PROCEDURE TO [ALLIANCE\IAAS_Scripts_NONPRD_DDL_ADMIN]
GO
GRANT ALTER TO [ALLIANCE\IAAS_Scripts_NONPRD_DDL_ADMIN]
GO
