WITH rebuilds AS (
SELECT * FROM OPENQUERY(SERVINFO, '
	SELECT *
	FROM CCDB2.MDB_DURATION
	WHERE ACTION = ''REBUILD''
	AND START_TS > CURRENT TIMESTAMP - 7 DAYS
	AND DBMS_INSTANCE_NM = ''SQL''
	AND DB_NM NOT IN (''MASTER'', ''MODEL'', ''MSDB'', ''TEMPDB'', 
		''SQLADMIN'', ''REPORTSERVER'', ''REPORTSERVERTEMPDB'')'))

SELECT SRVR_NM Server,
DATENAME(weekday, START_TS) Day, 
COUNT(DATENAME(weekday, START_TS)) DayCount, 
DATEPART(HOUR, START_TS) Hour, 
DATEPART(MINUTE, DATEADD(MINUTE, ROUND(DATEDIFF(MINUTE, 0, START_TS) / 15.0, 0) * 15, 0)) Minute
FROM rebuilds
GROUP BY SRVR_NM, 
DATENAME(weekday, START_TS),
DATEPART(HOUR, START_TS), 
DATEPART(MINUTE, DATEADD(MINUTE, ROUND(DATEDIFF(MINUTE, 0, START_TS) / 15.0, 0) * 15, 0))
ORDER BY Server, DayCount DESC



WITH rebuilds AS (
SELECT * FROM OPENQUERY(SERVINFO, '
	SELECT *
	FROM CCDB2.MDB_DURATION
	WHERE ACTION = ''INTEGRITY''
	AND START_TS > CURRENT TIMESTAMP - 7 DAYS
	AND DBMS_INSTANCE_NM = ''SQL''
	AND DB_NM NOT IN (''MASTER'', ''MODEL'', ''MSDB'', ''TEMPDB'', 
		''SQLADMIN'', ''REPORTSERVER'', ''REPORTSERVERTEMPDB'')'))

SELECT SRVR_NM Server,
DATENAME(weekday, START_TS) Day, 
COUNT(DATENAME(weekday, START_TS)) DayCount, 
DATEPART(HOUR, START_TS) Hour, 
DATEPART(MINUTE, DATEADD(MINUTE, ROUND(DATEDIFF(MINUTE, 0, START_TS) / 15.0, 0) * 15, 0)) Minute
FROM rebuilds
GROUP BY SRVR_NM, 
DATENAME(weekday, START_TS),
DATEPART(HOUR, START_TS), 
DATEPART(MINUTE, DATEADD(MINUTE, ROUND(DATEDIFF(MINUTE, 0, START_TS) / 15.0, 0) * 15, 0))
ORDER BY Server, DayCount DESC