SELECT 'ALTER TABLE [' + TABLE_NAME + '] ADD CONSTRAINT FK_' + TABLE_NAME + '_MonitoredServer FOREIGN KEY (InstanceID) REFERENCES Perf_MonitoredServers (InstanceID);'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE COLUMN_NAME = 'InstanceID' 
AND TABLE_NAME <> 'Perf_MonitoredServers'
ORDER BY TABLE_NAME


SELECT 'ALTER TABLE [' + TABLE_NAME + '] ALTER COLUMN InstanceID smallint'
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE COLUMN_NAME = 'InstanceID' 
AND DATA_TYPE = 'int'