USE master;
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD='k5evulch7QqW6rMF'; 
GO


USE master;
GO 
CREATE CERTIFICATE C1DBD067_TDE_FNCDB0A1_CERTIFICATE     
       WITH SUBJECT='Certificate for FNCDB0A1';
GO

USE master;
GO 
CREATE CERTIFICATE C1DBD067_TDE_FNCDB0P1_CERTIFICATE     
       WITH SUBJECT='Certificate for FNCDB0P1';
GO

EXEC xp_create_subdir '\\s01ddaesd001d\01_sqltestcifs\COLD_STORAGE\ENCRYPTION\C1DBD067'

USE master;
GO
BACKUP CERTIFICATE C1DBD067_TDE_FNCDB0A1_CERTIFICATE
TO FILE = '\\s01ddaesd001d\01_sqltestcifs\COLD_STORAGE\ENCRYPTION\C1DBD067\C1DBD067_TDE_FNCDB0A1_CERTIFICATE.cer'
WITH PRIVATE KEY (file='\\s01ddaesd001d\01_sqltestcifs\COLD_STORAGE\ENCRYPTION\C1DBD067\C1DBD067_TDE_FNCDB0A1_CERTIFICATE.pvk',
ENCRYPTION BY PASSWORD='CxDV3zryeIAgduYj');

USE master;
GO
BACKUP CERTIFICATE C1DBD067_TDE_FNCDB0P1_CERTIFICATE
TO FILE = '\\s01ddaesd001d\01_sqltestcifs\COLD_STORAGE\ENCRYPTION\C1DBD067\C1DBD067_TDE_FNCDB0P1_CERTIFICATE.cer'
WITH PRIVATE KEY (file='\\s01ddaesd001d\01_sqltestcifs\COLD_STORAGE\ENCRYPTION\C1DBD067\C1DBD067_TDE_FNCDB0P1_CERTIFICATE.pvk',
ENCRYPTION BY PASSWORD='UnuF1Ko9eOTly9wA');


BACKUP MASTER KEY TO FILE = '\\s01ddaesd001d\01_sqltestcifs\COLD_STORAGE\ENCRYPTION\C1DBD067\C1DBD067_TDE_MASTER_BACKUP.bak'   
    ENCRYPTION BY PASSWORD = 'xrvwa6Vf89OhMW5l'


USE FNCDB0A1
GO
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE C1DBD067_TDE_FNCDB0A1_CERTIFICATE;  
GO


USE FNCDB0P1
GO
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE C1DBD067_TDE_FNCDB0P1_CERTIFICATE;  
GO


ALTER DATABASE FNCDB0A1 SET ENCRYPTION ON;
GO
ALTER DATABASE FNCDB0P1 SET ENCRYPTION ON;
GO

USE MASTER
GO
SELECT
    db.name,
    db.is_encrypted,
    dm.encryption_state,
    dm.percent_complete,
    dm.key_algorithm,
    dm.key_length
FROM
    sys.databases db
    LEFT OUTER JOIN sys.dm_database_encryption_keys dm
        ON db.database_id = dm.database_id;
GO
